from PianoKeys import *
import time

class Songs:
    def londonBridge():
        pag.click(220, 200)
        Keys.c2()
        Keys.g3()
        Keys.a3()
        Keys.g2()
        Keys.g3()
        Keys.f3()
        Keys.c2()
        Keys.e3()
        Keys.f3()
        Keys.g2()
        Keys.g3()
        Keys.b1()
        Keys.d3()
        Keys.e3()
        Keys.g2()
        Keys.f3()
        Keys.c2()
        Keys.e3()
        Keys.f3()
        Keys.g2()
        Keys.g3()
        Keys.c2()
        Keys.g3()
        Keys.a3()
        Keys.g2()
        Keys.g3()
        Keys.f3()
        Keys.c2()
        Keys.e3()
        Keys.f3()
        Keys.g2()
        Keys.g3()
        Keys.b2()
        Keys.d3()
        Keys.g2()
        Keys.g3()
        Keys.c2()
        Keys.e3()
        Keys.c3()
